<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ko_KR">
<context>
    <name>AdvancedConfigPage</name>
    <message>
        <location filename="app/advancedconfigpage.ui" line="17"/>
        <source>Cache:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/advancedconfigpage.ui" line="29"/>
        <source>Delete thumbnail cache folder on exit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/advancedconfigpage.ui" line="51"/>
        <source>Enable this option if you do not have a lot of disk space.&lt;br/&gt;&lt;br/&gt;&lt;em&gt;Be careful:&lt;/em&gt; this will delete the folder named &lt;filename&gt;.thumbnails&lt;/filename&gt; in your home folder, deleting all thumbnails previously generated by Qroilib and other applications.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/advancedconfigpage.ui" line="77"/>
        <source>History:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/advancedconfigpage.ui" line="89"/>
        <source>Remember folders and URLs</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>DialogModel</name>
    <message>
        <location filename="app/dialogmodel.ui" line="78"/>
        <source>Model</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/dialogmodel.ui" line="98"/>
        <source>Exit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/dialogmodel.ui" line="149"/>
        <source>Add</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/dialogmodel.ui" line="170"/>
        <location filename="app/dialogmodel.cpp" line="80"/>
        <source>Change</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/dialogmodel.ui" line="191"/>
        <location filename="app/dialogmodel.cpp" line="70"/>
        <source>Delete</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/dialogmodel.cpp" line="70"/>
        <source>Do you want to delete?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/dialogmodel.cpp" line="80"/>
        <source>Do you want to change?</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>GeneralConfigPage</name>
    <message>
        <location filename="app/generalconfigpage.ui" line="17"/>
        <source>Background color:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/generalconfigpage.ui" line="82"/>
        <source>Videos:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/generalconfigpage.ui" line="89"/>
        <source>Show videos</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ImageViewConfigPage</name>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="17"/>
        <source>Transparent background:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="38"/>
        <source>&amp;Check board</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="71"/>
        <source>&amp;Solid color:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="119"/>
        <source>Mouse wheel behavior:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="134"/>
        <source>Scroll</source>
        <comment>@option:radio action on mouse wheel</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="161"/>
        <source>Browse</source>
        <comment>@option:radio action on mouse wheel</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="199"/>
        <source>Zoom mode:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="214"/>
        <source>Autofit each image</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="241"/>
        <source>Keep same zoom and position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="265"/>
        <source>Per image zoom and position</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="305"/>
        <source>Enlarge smaller images</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="343"/>
        <source>Animations:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="358"/>
        <source>OpenGL</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="385"/>
        <source>Software</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="409"/>
        <source>None</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="447"/>
        <source>&lt;b&gt;Thumbnail Bar&lt;/b&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="470"/>
        <source>Orientation:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="485"/>
        <source>Horizontal</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="509"/>
        <source>Vertical</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/imageviewconfigpage.ui" line="531"/>
        <source>Row count:</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="app/mainwindow.cpp" line="141"/>
        <source>&amp;Select ...</source>
        <translation type="unfinished">선택(&amp;S)...</translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="145"/>
        <source>Create &amp;Rectangle...</source>
        <translation type="unfinished">사각ROI생성(&amp;R)...</translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="148"/>
        <source>Create p&amp;Oint...</source>
        <translation type="unfinished">포인터ROI생성(&amp;O)...</translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="151"/>
        <source>Create &amp;Pattern ROI...</source>
        <translation type="unfinished">패턴ROI생성(&amp;P)...</translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="154"/>
        <source>&amp;load RoiMap ...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="156"/>
        <source>&amp;write RoiMap ...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="159"/>
        <source>E&amp;xit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="163"/>
        <source>layer&amp;1 ...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="165"/>
        <source>layer&amp;2 ...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="168"/>
        <source>&amp;File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="180"/>
        <source>&amp;Device</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="194"/>
        <source>&amp;Layer</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="263"/>
        <source>Layer1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="264"/>
        <source>Layer2</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="397"/>
        <source>Close application</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/mainwindow.cpp" line="400"/>
        <source>Do you really want to quit?</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ObjectTypes</name>
    <message>
        <location filename="qroilib/roilib/objecttypes.cpp" line="42"/>
        <source>Could not open file for writing.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/objecttypes.cpp" line="106"/>
        <source>Could not open file.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/objecttypes.cpp" line="116"/>
        <source>File doesn&apos;t contain object types.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/objecttypes.cpp" line="143"/>
        <source>%3

Line %1, column %2</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>PreferencesDialog</name>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="76"/>
        <source>XML</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="77"/>
        <source>Base64 (uncompressed)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="78"/>
        <source>Base64 (gzip compressed)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="79"/>
        <source>Base64 (zlib compressed)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="80"/>
        <source>CSV</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="82"/>
        <source>Right Down</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="83"/>
        <source>Right Up</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="84"/>
        <source>Left Down</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="85"/>
        <source>Left Up</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ProgressDialog</name>
    <message>
        <location filename="app/common.h" line="91"/>
        <source>Motor Origin Executing...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="app/common.h" line="93"/>
        <source>...is executing the Motor Origin...
Wait a moment...</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="qroilib/documentview/documentviewcontroller.cpp" line="97"/>
        <source>Fit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/documentview/documentviewcontroller.cpp" line="98"/>
        <source>Fit:button Zoom to fit, shown in status bar, keep it short please</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/documentview/documentviewcontroller.cpp" line="103"/>
        <source>100%</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/documentview/documentviewcontroller.cpp" line="104"/>
        <source>100%:button Zoom to original size, shown in status bar, keep it short please</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/documentview/documentviewcontroller.cpp" line="107"/>
        <source>+</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/documentview/documentviewcontroller.cpp" line="108"/>
        <source>+:button ZoomIn, shown in status bar, keep it short please</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/documentview/documentviewcontroller.cpp" line="110"/>
        <source>-</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/documentview/documentviewcontroller.cpp" line="111"/>
        <source>-:button ZoomOut, shown in status bar, keep it short please</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QextSerialPort</name>
    <message>
        <location filename="serial/qextserialport.cpp" line="722"/>
        <source>No Error has occurred</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="724"/>
        <source>Invalid file descriptor (port was not opened correctly)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="726"/>
        <source>Unable to allocate memory tables (POSIX)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="728"/>
        <source>Caught a non-blocked signal (POSIX)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="730"/>
        <source>Operation timed out (POSIX)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="732"/>
        <source>The file opened by the port is not a valid device</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="734"/>
        <source>The port detected a break condition</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="736"/>
        <source>The port detected a framing error (usually caused by incorrect baud rate settings)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="738"/>
        <source>There was an I/O error while communicating with the port</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="740"/>
        <source>Character buffer overrun</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="742"/>
        <source>Receive buffer overflow</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="744"/>
        <source>The port detected a parity error in the received data</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="746"/>
        <source>Transmit buffer overflow</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="748"/>
        <source>General read operation failure</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="750"/>
        <source>General write operation failure</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="752"/>
        <source>The %1 file doesn&apos;t exists</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="754"/>
        <source>Permission denied</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="756"/>
        <source>Device is already locked</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="serial/qextserialport.cpp" line="758"/>
        <source>Unknown error: %1</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::AbstractObjectTool</name>
    <message numerus="yes">
        <location filename="qroilib/roilib/abstractobjecttool.cpp" line="221"/>
        <source>Duplicate %n Object(s)</source>
        <translation type="unfinished">
            <numerusform></numerusform>
        </translation>
    </message>
    <message numerus="yes">
        <location filename="qroilib/roilib/abstractobjecttool.cpp" line="223"/>
        <source>Remove %n Object(s)</source>
        <translation type="unfinished">
            <numerusform></numerusform>
        </translation>
    </message>
    <message>
        <location filename="qroilib/roilib/abstractobjecttool.cpp" line="234"/>
        <source>Reset Tile Size</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/abstractobjecttool.cpp" line="241"/>
        <source>Flip Horizontally</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/abstractobjecttool.cpp" line="241"/>
        <source>X</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/abstractobjecttool.cpp" line="242"/>
        <source>Flip Vertically</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/abstractobjecttool.cpp" line="242"/>
        <source>Y</source>
        <translation type="unfinished"></translation>
    </message>
    <message numerus="yes">
        <location filename="qroilib/roilib/abstractobjecttool.cpp" line="255"/>
        <source>Move %n Object(s) to Layer</source>
        <translation type="unfinished">
            <numerusform></numerusform>
        </translation>
    </message>
    <message>
        <location filename="qroilib/roilib/abstractobjecttool.cpp" line="266"/>
        <source>Object &amp;Properties...</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::CreateEllipseObjectTool</name>
    <message>
        <location filename="qroilib/roilib/createellipseobjecttool.cpp" line="38"/>
        <source>Insert Ellipse</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/createellipseobjecttool.cpp" line="39"/>
        <source>C</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::CreateObjectTool</name>
    <message>
        <location filename="qroilib/roilib/createobjecttool.cpp" line="45"/>
        <source>O</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::CreatePatternObjectTool</name>
    <message>
        <location filename="qroilib/roilib/createpatternobjecttool.cpp" line="38"/>
        <source>Insert PatternROI</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/createpatternobjecttool.cpp" line="39"/>
        <source>P</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::CreatePointObjectTool</name>
    <message>
        <location filename="qroilib/roilib/createpointobjecttool.cpp" line="38"/>
        <source>Insert Point</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/createpointobjecttool.cpp" line="39"/>
        <source>P</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::CreatePolygonObjectTool</name>
    <message>
        <location filename="qroilib/roilib/createpolygonobjecttool.cpp" line="38"/>
        <source>Insert Polygon</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/createpolygonobjecttool.cpp" line="39"/>
        <source>P</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::CreatePolylineObjectTool</name>
    <message>
        <location filename="qroilib/roilib/createpolylineobjecttool.cpp" line="38"/>
        <source>Insert Polyline</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/createpolylineobjecttool.cpp" line="39"/>
        <source>L</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::CreateRectangleObjectTool</name>
    <message>
        <location filename="qroilib/roilib/createrectangleobjecttool.cpp" line="38"/>
        <source>Insert Rectangle</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/createrectangleobjecttool.cpp" line="39"/>
        <source>R</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::CreateTextObjectTool</name>
    <message>
        <location filename="qroilib/roilib/createtextobjecttool.cpp" line="70"/>
        <source>Insert Text</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/createtextobjecttool.cpp" line="71"/>
        <source>X</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/createtextobjecttool.cpp" line="77"/>
        <source>Hello World</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::DocumentView</name>
    <message>
        <location filename="qroilib/documentview/documentview.cpp" line="359"/>
        <source>Qroilib does not know how to display this kind of document</source>
        <translation type="unfinished"></translation>
    </message>
    <message numerus="yes">
        <location filename="qroilib/documentview/documentview.cpp" line="910"/>
        <source>Duplicate %n Object(s)</source>
        <translation type="unfinished">
            <numerusform></numerusform>
        </translation>
    </message>
    <message numerus="yes">
        <location filename="qroilib/documentview/documentview.cpp" line="932"/>
        <source>Remove %n Object(s)</source>
        <translation type="unfinished">
            <numerusform></numerusform>
        </translation>
    </message>
</context>
<context>
    <name>Qroilib::EditPolygonTool</name>
    <message>
        <location filename="qroilib/roilib/editpolygontool.cpp" line="128"/>
        <location filename="qroilib/roilib/editpolygontool.cpp" line="349"/>
        <source>Edit Polygons</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/editpolygontool.cpp" line="130"/>
        <location filename="qroilib/roilib/editpolygontool.cpp" line="350"/>
        <source>E</source>
        <translation type="unfinished"></translation>
    </message>
    <message numerus="yes">
        <location filename="qroilib/roilib/editpolygontool.cpp" line="575"/>
        <source>Move %n Point(s)</source>
        <translation type="unfinished">
            <numerusform></numerusform>
        </translation>
    </message>
    <message numerus="yes">
        <location filename="qroilib/roilib/editpolygontool.cpp" line="601"/>
        <location filename="qroilib/roilib/editpolygontool.cpp" line="646"/>
        <source>Delete %n Node(s)</source>
        <translation type="unfinished">
            <numerusform></numerusform>
        </translation>
    </message>
    <message>
        <location filename="qroilib/roilib/editpolygontool.cpp" line="606"/>
        <location filename="qroilib/roilib/editpolygontool.cpp" line="821"/>
        <source>Join Nodes</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/editpolygontool.cpp" line="607"/>
        <location filename="qroilib/roilib/editpolygontool.cpp" line="857"/>
        <source>Split Segments</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::LayerOffsetTool</name>
    <message>
        <location filename="qroilib/roilib/layeroffsettool.cpp" line="41"/>
        <location filename="qroilib/roilib/layeroffsettool.cpp" line="135"/>
        <source>Offset Layers</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/layeroffsettool.cpp" line="43"/>
        <location filename="qroilib/roilib/layeroffsettool.cpp" line="136"/>
        <source>M</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::MessageViewAdapter</name>
    <message>
        <location filename="qroilib/documentview/messageviewadapter.cpp" line="49"/>
        <source>No document selected</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::ObjectSelectionTool</name>
    <message>
        <location filename="qroilib/roilib/objectselectiontool.cpp" line="302"/>
        <location filename="qroilib/roilib/objectselectiontool.cpp" line="714"/>
        <source>Select Objects</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/objectselectiontool.cpp" line="304"/>
        <location filename="qroilib/roilib/objectselectiontool.cpp" line="715"/>
        <source>S</source>
        <translation type="unfinished"></translation>
    </message>
    <message numerus="yes">
        <location filename="qroilib/roilib/objectselectiontool.cpp" line="417"/>
        <location filename="qroilib/roilib/objectselectiontool.cpp" line="1163"/>
        <source>Move %n Object(s)</source>
        <translation type="unfinished">
            <numerusform></numerusform>
        </translation>
    </message>
    <message>
        <location filename="qroilib/roilib/objectselectiontool.cpp" line="563"/>
        <source>Unnamed object</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/objectselectiontool.cpp" line="565"/>
        <source>Instance of %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/objectselectiontool.cpp" line="569"/>
        <source>&amp;%1) %2</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/objectselectiontool.cpp" line="571"/>
        <source>%1) %2</source>
        <translation type="unfinished"></translation>
    </message>
    <message numerus="yes">
        <location filename="qroilib/roilib/objectselectiontool.cpp" line="1460"/>
        <source>Resize %n Object(s)</source>
        <translation type="unfinished">
            <numerusform></numerusform>
        </translation>
    </message>
</context>
<context>
    <name>Qroilib::ObjectTypesModel</name>
    <message>
        <location filename="qroilib/roilib/objecttypesmodel.cpp" line="58"/>
        <source>Type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/objecttypesmodel.cpp" line="60"/>
        <source>Color</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::PropertiesDock</name>
    <message>
        <location filename="qroilib/roilib/propertiesdock.cpp" line="250"/>
        <source>Convert To</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertiesdock.cpp" line="251"/>
        <source>Rename...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertiesdock.cpp" line="252"/>
        <source>Remove</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertiesdock.cpp" line="317"/>
        <source>Properties</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::PropertyBrowser</name>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="62"/>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="381"/>
        <source>X</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="63"/>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="382"/>
        <source>Y</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="65"/>
        <source>Odd</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="66"/>
        <source>Even</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="87"/>
        <source>Horizontal</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="88"/>
        <source>Vertical</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="90"/>
        <source>Top Down</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="91"/>
        <source>Manual</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="307"/>
        <source>RoiMap</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="312"/>
        <source>Orientation</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="317"/>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="387"/>
        <source>Width</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="318"/>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="388"/>
        <source>Height</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="319"/>
        <source>RoiMap Width</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="320"/>
        <source>RoiMap Height</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="322"/>
        <source>RoiMap Side Length (Hex)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="327"/>
        <source>Stagger Axis</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="335"/>
        <source>Stagger Index</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="343"/>
        <source>Tile Layer Format</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="351"/>
        <source>Tile Render Order</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="356"/>
        <source>Background Color</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="371"/>
        <source>Object</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="373"/>
        <source>ID</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="374"/>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="406"/>
        <source>Name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="377"/>
        <source>Type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="380"/>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="407"/>
        <source>Visible</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="391"/>
        <source>Rotation</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="394"/>
        <source>Text</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="396"/>
        <source>Font</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="397"/>
        <source>Word Wrap</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="398"/>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="431"/>
        <source>Color</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="410"/>
        <source>Opacity</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="415"/>
        <source>Horizontal Offset</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="416"/>
        <source>Vertical Offset</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="421"/>
        <source>Tile Layer</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="428"/>
        <source>Object Layer</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="436"/>
        <source>Drawing Order</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="446"/>
        <source>Group Layer</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="571"/>
        <source>Custom Properties</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::RoiObjectModel</name>
    <message>
        <location filename="qroilib/roilib/roiobjectmodel.cpp" line="206"/>
        <source>Name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/roiobjectmodel.cpp" line="207"/>
        <source>Type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/roiobjectmodel.cpp" line="208"/>
        <source>ID</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/roiobjectmodel.cpp" line="209"/>
        <source>Position</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Qroilib::VariantManager</name>
    <message>
        <location filename="qroilib/variantmanager.cpp" line="77"/>
        <source>(%1, %2)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/variantmanager.cpp" line="113"/>
        <source>Position X</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/variantmanager.cpp" line="118"/>
        <source>Position Y</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtBoolEdit</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="243"/>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="253"/>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="278"/>
        <source>True</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="253"/>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="278"/>
        <source>False</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtBoolPropertyManager</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="1703"/>
        <source>True</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="1704"/>
        <source>False</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtCharEdit</name>
    <message>
        <location filename="qtpropertybrowser/src/qteditorfactory.cpp" line="1712"/>
        <source>Clear Char</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtColorEditWidget</name>
    <message>
        <location filename="qtpropertybrowser/src/qteditorfactory.cpp" line="2326"/>
        <source>...</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtColorPropertyManager</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="6440"/>
        <source>Red</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="6448"/>
        <source>Green</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="6456"/>
        <source>Blue</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="6464"/>
        <source>Alpha</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtCursorDatabase</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="58"/>
        <source>Arrow</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="60"/>
        <source>Up Arrow</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="62"/>
        <source>Cross</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="64"/>
        <source>Wait</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="66"/>
        <source>IBeam</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="68"/>
        <source>Size Vertical</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="70"/>
        <source>Size Horizontal</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="72"/>
        <source>Size Backslash</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="74"/>
        <source>Size Slash</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="76"/>
        <source>Size All</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="78"/>
        <source>Blank</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="80"/>
        <source>Split Vertical</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="82"/>
        <source>Split Horizontal</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="84"/>
        <source>Pointing Hand</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="86"/>
        <source>Forbidden</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="88"/>
        <source>Open Hand</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="90"/>
        <source>Closed Hand</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="92"/>
        <source>What&apos;s This</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="94"/>
        <source>Busy</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtFontEditWidget</name>
    <message>
        <location filename="qtpropertybrowser/src/qteditorfactory.cpp" line="2535"/>
        <source>...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qteditorfactory.cpp" line="2555"/>
        <source>Select Font</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtFontPropertyManager</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="6102"/>
        <source>Family</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="6115"/>
        <source>Pixel Size</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="6123"/>
        <source>Bold</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="6130"/>
        <source>Italic</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="6137"/>
        <source>Underline</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="6144"/>
        <source>Strikeout</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="6151"/>
        <source>Kerning</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtKeySequenceEdit</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="338"/>
        <source>Clear Shortcut</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtLocalePropertyManager</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="2618"/>
        <source>%1, %2</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="2671"/>
        <source>Language</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="2679"/>
        <source>Country</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtPointFPropertyManager</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="3088"/>
        <source>(%1, %2)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="3159"/>
        <source>X</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="3167"/>
        <source>Y</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtPointPropertyManager</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="2848"/>
        <source>(%1, %2)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="2885"/>
        <source>X</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="2892"/>
        <source>Y</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtPropertyBrowserUtils</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="188"/>
        <source>[%1, %2, %3] (%4)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="191"/>
        <source>Not set</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertybrowserutils.cpp" line="224"/>
        <source>[%1, %2]</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtRectFPropertyManager</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="4593"/>
        <source>[(%1, %2), %3 x %4]</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="4749"/>
        <source>X</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="4757"/>
        <source>Y</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="4765"/>
        <source>Width</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="4774"/>
        <source>Height</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtRectPropertyManager</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="4163"/>
        <source>[(%1, %2), %3 x %4]</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="4283"/>
        <source>X</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="4290"/>
        <source>Y</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="4297"/>
        <source>Width</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="4305"/>
        <source>Height</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtSizeFPropertyManager</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="3771"/>
        <source>%1 x %2</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="3901"/>
        <source>Width</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="3910"/>
        <source>Height</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtSizePolicyPropertyManager</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="5614"/>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="5615"/>
        <source>&lt;Invalid&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="5616"/>
        <source>[%1, %2, %3, %4]</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="5661"/>
        <source>Horizontal Policy</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="5670"/>
        <source>Vertical Policy</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="5679"/>
        <source>Horizontal Stretch</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="5687"/>
        <source>Vertical Stretch</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtSizePropertyManager</name>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="3407"/>
        <source>%1 x %2</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="3503"/>
        <source>Width</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qtpropertymanager.cpp" line="3511"/>
        <source>Height</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QtTreePropertyBrowser</name>
    <message>
        <location filename="qtpropertybrowser/src/qttreepropertybrowser.cpp" line="504"/>
        <source>Property</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qtpropertybrowser/src/qttreepropertybrowser.cpp" line="505"/>
        <source>Value</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ResizeImageWidget</name>
    <message>
        <location filename="qroilib/resize/resizeimagewidget.ui" line="14"/>
        <source>Image Resizing</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/resize/resizeimagewidget.ui" line="20"/>
        <source>Enter the new size for this image.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/resize/resizeimagewidget.ui" line="32"/>
        <source>Current size:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/resize/resizeimagewidget.ui" line="88"/>
        <source>New Si&amp;ze:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/resize/resizeimagewidget.ui" line="129"/>
        <source>Keep aspect ratio</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>RoiReader</name>
    <message>
        <location filename="qroilib/roilib/roireader.cpp" line="115"/>
        <source>Not a roimap file.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/roireader.cpp" line="128"/>
        <source>%3

Line %1, column %2</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/roireader.cpp" line="138"/>
        <source>File not found: %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/roireader.cpp" line="141"/>
        <source>Unable to read file: %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/roireader.cpp" line="173"/>
        <location filename="qroilib/roilib/varianttomapconverter.cpp" line="53"/>
        <source>Unsupported roimap orientation: &quot;%1&quot;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/roireader.cpp" line="279"/>
        <location filename="qroilib/roilib/varianttomapconverter.cpp" line="168"/>
        <source>Invalid draw order: %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/roireader.cpp" line="461"/>
        <source>Invalid points data for polygon</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/roiwriter.cpp" line="101"/>
        <source>Could not open file for writing.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Tiled::Internal::NewMapDialog</name>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="68"/>
        <source>Orthogonal</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="69"/>
        <source>Isometric</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="70"/>
        <source>Isometric (Staggered)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/propertybrowser.cpp" line="71"/>
        <source>Hexagonal (Staggered)</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Undo Commands</name>
    <message>
        <location filename="qroilib/roilib/addremoveroiobject.cpp" line="111"/>
        <source>Add Object</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/addremoveroiobject.cpp" line="124"/>
        <source>Remove Object</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/changeobjectgroupproperties.cpp" line="39"/>
        <source>Change Object Layer Properties</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/changepolygon.cpp" line="40"/>
        <location filename="qroilib/roilib/changepolygon.cpp" line="52"/>
        <source>Change Polygon</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/changeproperties.cpp" line="40"/>
        <source>Change %1 Properties</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/changeproperties.cpp" line="81"/>
        <source>Set Property</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/changeproperties.cpp" line="83"/>
        <source>Add Property</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/changeproperties.cpp" line="116"/>
        <source>Remove Property</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/changeproperties.cpp" line="138"/>
        <source>Rename Property</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/changeselectedarea.cpp" line="33"/>
        <source>Change Selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/moveroiobject.cpp" line="42"/>
        <location filename="qroilib/roilib/moveroiobject.cpp" line="56"/>
        <source>Move Object</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/moveroiobjecttogroup.cpp" line="41"/>
        <source>Move Object to Layer</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/resizeroiobject.cpp" line="40"/>
        <location filename="qroilib/roilib/resizeroiobject.cpp" line="52"/>
        <source>Resize Object</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="qroilib/roilib/rotateroiobject.cpp" line="40"/>
        <location filename="qroilib/roilib/rotateroiobject.cpp" line="52"/>
        <source>Rotate Object</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Utils</name>
    <message>
        <location filename="qroilib/roilib/utils.cpp" line="39"/>
        <source>Image files</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
