#ifndef QROILIB_VERSION_H
#define QROILIB_VERSION_H

#define QROILIB_VERSION_STRING "0.0.1"
#define QROILIB_VERSION_MAJOR 0
#define QROILIB_VERSION_MINOR 0
#define QROILIB_VERSION_PATCH 1
#define QROILIB_VERSION ((16<<16)|(11<<8)|(70))

#endif
