
DEFINES += ROID_LIBRARY
DEFINES += QEXTSERIALPORT_BUILD_SHARED

include(./qtpropertybrowser/src/qtpropertybrowser.pri)

win32 {
INCLUDEPATH += "C:\opencv\buildQT\include"
}

linux {
QMAKE_CXXFLAGS += -std=c++11
INCLUDEPATH += /usr/local/include
}

INCLUDEPATH += $$PWD \
   $$PWD/qroilib \
   $$PWD/qroilib/document \
   $$PWD/qroilib/roilib

# Input
HEADERS += $$PWD/engine/blob.h \
           $$PWD/engine/blobcontour.h \
           $$PWD/engine/bloblibraryconfiguration.h \
           $$PWD/engine/bloboperators.h \
           $$PWD/engine/blobproperties.h \
           $$PWD/engine/blobresult.h \
           $$PWD/engine/componentlabeling.h \
           $$PWD/engine/edgessubpix.h \
           $$PWD/engine/image_contour.h \
           $$PWD/engine/voronoithinner.h \
           $$PWD/engine/imgprocbase.h \
           $$PWD/qroilib/graphicswidgetfloater.h \
           $$PWD/qroilib/gvdebug.h \
           $$PWD/qroilib/imagescaler.h \
           $$PWD/qroilib/imageutils.h \
           $$PWD/qroilib/iodevicejpegsourcemanager.h \
           $$PWD/qroilib/jpegerrormanager.h \
           $$PWD/qroilib/memoryutils.h \
           $$PWD/qroilib/mimetypeutils.h \
           $$PWD/qroilib/mimetypeutils_p.h \
           $$PWD/qroilib/mousewheelbehavior.h \
           $$PWD/qroilib/orientation.h \
           $$PWD/qroilib/paintutils.h \
           $$PWD/qroilib/signalblocker.h \
           $$PWD/qroilib/statusbartoolbutton.h \
           $$PWD/qroilib/thumbnailgroup.h \
           $$PWD/qroilib/variantmanager.h \
           $$PWD/qroilib/widgetfloater.h \
           $$PWD/qroilib/zoommode.h \
           $$PWD/qroilib/zoomslider.h \
           $$PWD/qroilib/zoomwidget.h \
           $$PWD/qroilib/cms/cmsprofile.h \
           $$PWD/qroilib/cms/cmsprofile_png.h \
           $$PWD/qroilib/cms/iccjpeg.h \
           $$PWD/qroilib/document/abstractdocumenteditor.h \
           $$PWD/qroilib/document/abstractdocumentimpl.h \
           $$PWD/qroilib/document/document.h \
           $$PWD/qroilib/document/document_p.h \
           $$PWD/qroilib/document/documentfactory.h \
           $$PWD/qroilib/document/documentjob.h \
           $$PWD/qroilib/documentview/abstractdocumentviewadapter.h \
           $$PWD/qroilib/documentview/abstractimageview.h \
           $$PWD/qroilib/documentview/birdeyeview.h \
           $$PWD/qroilib/documentview/documentview.h \
           $$PWD/qroilib/documentview/documentviewcontainer.h \
           $$PWD/qroilib/documentview/documentviewcontroller.h \
           $$PWD/qroilib/documentview/messageviewadapter.h \
           $$PWD/qroilib/documentview/rasterimageview.h \
           $$PWD/qroilib/documentview/rasterimageviewadapter.h \
           $$PWD/qroilib/jconfig.h \
           $$PWD/qroilib/jmorecfg.h \
           $$PWD/qroilib/jpeglib.h \
           $$PWD/qroilib/lcms2.h \
           $$PWD/qroilib/png.h \
           $$PWD/qroilib/pngconf.h \
           $$PWD/qroilib/zconf.h \
           $$PWD/qroilib/zlib.h \
           $$PWD/qroilib/roilib/abstractobjecttool.h \
           $$PWD/qroilib/roilib/abstracttool.h \
           $$PWD/qroilib/roilib/addremoveroiobject.h \
           $$PWD/qroilib/roilib/changeobjectgroupproperties.h \
           $$PWD/qroilib/roilib/changepolygon.h \
           $$PWD/qroilib/roilib/changeproperties.h \
           $$PWD/qroilib/roilib/changeselectedarea.h \
           $$PWD/qroilib/roilib/compression.h \
           $$PWD/qroilib/roilib/createellipseobjecttool.h \
           $$PWD/qroilib/roilib/createmultipointobjecttool.h \
           $$PWD/qroilib/roilib/createobjecttool.h \
           $$PWD/qroilib/roilib/createpatternobjecttool.h \
           $$PWD/qroilib/roilib/createpointobjecttool.h \
           $$PWD/qroilib/roilib/createpolygonobjecttool.h \
           $$PWD/qroilib/roilib/createpolylineobjecttool.h \
           $$PWD/qroilib/roilib/createrectangleobjecttool.h \
           $$PWD/qroilib/roilib/createscalableobjecttool.h \
           $$PWD/qroilib/roilib/createtextobjecttool.h \
           $$PWD/qroilib/roilib/editpolygontool.h \
           $$PWD/qroilib/roilib/filesystemwatcher.h \
           $$PWD/qroilib/roilib/grouplayer.h \
           $$PWD/qroilib/roilib/hex.h \
           $$PWD/qroilib/roilib/hexagonalrenderer.h \
           $$PWD/qroilib/roilib/imagereference.h \
           $$PWD/qroilib/roilib/isometricrenderer.h \
           $$PWD/qroilib/roilib/layer.h \
           $$PWD/qroilib/roilib/layeritem.h \
           $$PWD/qroilib/roilib/layeroffsettool.h \
           $$PWD/qroilib/roilib/logginginterface.h \
           $$PWD/qroilib/roilib/moveroiobject.h \
           $$PWD/qroilib/roilib/moveroiobjecttogroup.h \
           $$PWD/qroilib/roilib/object.h \
           $$PWD/qroilib/roilib/objectgroup.h \
           $$PWD/qroilib/roilib/objectgroupitem.h \
           $$PWD/qroilib/roilib/objectselectionitem.h \
           $$PWD/qroilib/roilib/objectselectiontool.h \
           $$PWD/qroilib/roilib/objecttypes.h \
           $$PWD/qroilib/roilib/objecttypesmodel.h \
           $$PWD/qroilib/roilib/orthogonalrenderer.h \
           $$PWD/qroilib/roilib/properties.h \
           $$PWD/qroilib/roilib/propertiesdock.h \
           $$PWD/qroilib/roilib/propertybrowser.h \
           $$PWD/qroilib/roilib/qpatternroif.h \
           $$PWD/qroilib/roilib/rangeset.h \
           $$PWD/qroilib/roilib/resizeroiobject.h \
           $$PWD/qroilib/roilib/roid.h \
           $$PWD/qroilib/roilib/roid_global.h \
           $$PWD/qroilib/roilib/roilib_export.h \
           $$PWD/qroilib/roilib/roilib_version.h \
           $$PWD/qroilib/roilib/roimap.h \
           $$PWD/qroilib/roilib/roiobject.h \
           $$PWD/qroilib/roilib/roiobjectitem.h \
           $$PWD/qroilib/roilib/roiobjectmodel.h \
           $$PWD/qroilib/roilib/roireader.h \
           $$PWD/qroilib/roilib/roirenderer.h \
           $$PWD/qroilib/roilib/roiscene.h \
           $$PWD/qroilib/roilib/roitovariantconverter.h \
           $$PWD/qroilib/roilib/roiwriter.h \
           $$PWD/qroilib/roilib/rotateroiobject.h \
           $$PWD/qroilib/roilib/savefile.h \
           $$PWD/qroilib/roilib/selectionrectangle.h \
           $$PWD/qroilib/roilib/snaphelper.h \
           $$PWD/qroilib/roilib/toolmanager.h \
           $$PWD/qroilib/roilib/utils.h \
           $$PWD/qroilib/roilib/variantpropertymanager.h \
           $$PWD/qroilib/roilib/varianttomapconverter.h \
           $$PWD/qroilib/roilib/objectgroup.h \
           $$PWD/qroilib/roilib/roilib_export.h \
           $$PWD/qroilib/document/document.h \
           $$PWD/qroilib/mimetypeutils.h \
           $$PWD/qroilib/cms/cmsprofile.h \
           $$PWD/qroilib/paintutils.h \
           $$PWD/qroilib/orientation.h \
           $$PWD/qroilib/jpeglib.h \
           $$PWD/qroilib/gvdebug.h \
           $$PWD/qroilib/statusbartoolbutton.h \
           $$PWD/qroilib/cms/cmsprofile_png.h \
           $$PWD/qroilib/jpegerrormanager.h \
           $$PWD/qroilib/cms/iccjpeg.h \
           $$PWD/qroilib/lcms2.h \
           $$PWD/qroilib/png.h \
           $$PWD/qroilib/document/documentjob.h \
           $$PWD/qroilib/document/abstractdocumentimpl.h \
           $$PWD/qroilib/documentview/documentview.h \
           $$PWD/qroilib/roilib/roiwriter.h \
           $$PWD/qroilib/document/documentfactory.h \
           $$PWD/qroilib/documentview/birdeyeview.h \
           $$PWD/qroilib/documentview/messageviewadapter.h \
           $$PWD/qroilib/documentview/abstractdocumentviewadapter.h \
           $$PWD/qroilib/documentview/rasterimageview.h \
           $$PWD/qroilib/documentview/abstractimageview.h \
           $$PWD/qroilib/documentview/rasterimageviewadapter.h \
           $$PWD/qroilib/graphicswidgetfloater.h \
           $$PWD/qroilib/signalblocker.h \
           $$PWD/qroilib/roilib/savefile.h \
           $$PWD/qroilib/roilib/roiscene.h \
           $$PWD/qroilib/roilib/roirenderer.h \
           $$PWD/qroilib/roilib/roireader.h \
           $$PWD/qroilib/roilib/addremoveroiobject.h \
           $$PWD/qroilib/roilib/grouplayer.h \
           $$PWD/qroilib/roilib/hexagonalrenderer.h \
           $$PWD/qroilib/roilib/orthogonalrenderer.h \
           $$PWD/qroilib/roilib/isometricrenderer.h \
           $$PWD/qroilib/roilib/layeroffsettool.h \
           $$PWD/qroilib/roilib/abstracttool.h \
           $$PWD/qroilib/roilib/roiobject.h \
           $$PWD/qroilib/roilib/roiobjectmodel.h \
           $$PWD/qroilib/roilib/toolmanager.h \
           $$PWD/qroilib/roilib/roiobjectitem.h \
           $$PWD/qroilib/roilib/objectselectiontool.h \
           $$PWD/qroilib/roilib/createellipseobjecttool.h \
           $$PWD/qroilib/roilib/createobjecttool.h \
           $$PWD/qroilib/roilib/createpolygonobjecttool.h \
           $$PWD/qroilib/roilib/createpolylineobjecttool.h \
           $$PWD/qroilib/roilib/createpointobjecttool.h \
           $$PWD/qroilib/roilib/createrectangleobjecttool.h \
           $$PWD/qroilib/roilib/createpatternobjecttool.h \
           $$PWD/qroilib/roilib/createtextobjecttool.h \
           $$PWD/qroilib/zoomwidget.h \
           $$PWD/qroilib/imagescaler.h \

FORMS += $$PWD/qroilib/documentview/messageview.ui \
         $$PWD/qroilib/resize/resizeimagewidget.ui

SOURCES += $$PWD/engine/blob.cpp \
           $$PWD/engine/blobcontour.cpp \
           $$PWD/engine/bloboperators.cpp \
           $$PWD/engine/blobproperties.cpp \
           $$PWD/engine/blobresult.cpp \
           $$PWD/engine/componentlabeling.cpp \
           $$PWD/engine/edgessubpix.cpp \
           $$PWD/engine/voronoithinner.cpp \
           $$PWD/engine/imgprocbase.cpp \
           $$PWD/qroilib/graphicswidgetfloater.cpp \
           $$PWD/qroilib/imagescaler.cpp \
           $$PWD/qroilib/imageutils.cpp \
           $$PWD/qroilib/iodevicejpegsourcemanager.cpp \
           $$PWD/qroilib/memoryutils.cpp \
           $$PWD/qroilib/mimetypeutils.cpp \
           $$PWD/qroilib/paintutils.cpp \
           $$PWD/qroilib/statusbartoolbutton.cpp \
           $$PWD/qroilib/variantmanager.cpp \
           $$PWD/qroilib/widgetfloater.cpp \
           $$PWD/qroilib/zoomslider.cpp \
           $$PWD/qroilib/zoomwidget.cpp \
           $$PWD/qroilib/cms/cmsprofile.cpp \
           $$PWD/qroilib/cms/cmsprofile_png.cpp \
           $$PWD/qroilib/cms/iccjpeg.c \
           $$PWD/qroilib/document/abstractdocumentimpl.cpp \
           $$PWD/qroilib/document/document.cpp \
           $$PWD/qroilib/document/documentfactory.cpp \
           $$PWD/qroilib/document/documentjob.cpp \
           $$PWD/qroilib/documentview/abstractdocumentviewadapter.cpp \
           $$PWD/qroilib/documentview/abstractimageview.cpp \
           $$PWD/qroilib/documentview/birdeyeview.cpp \
           $$PWD/qroilib/documentview/documentview.cpp \
           $$PWD/qroilib/documentview/documentviewcontainer.cpp \
           $$PWD/qroilib/documentview/documentviewcontroller.cpp \
           $$PWD/qroilib/documentview/messageviewadapter.cpp \
           $$PWD/qroilib/documentview/rasterimageview.cpp \
           $$PWD/qroilib/documentview/rasterimageviewadapter.cpp \
           $$PWD/qroilib/roilib/abstractobjecttool.cpp \
           $$PWD/qroilib/roilib/abstracttool.cpp \
           $$PWD/qroilib/roilib/addremoveroiobject.cpp \
           $$PWD/qroilib/roilib/changeobjectgroupproperties.cpp \
           $$PWD/qroilib/roilib/changepolygon.cpp \
           $$PWD/qroilib/roilib/changeproperties.cpp \
           $$PWD/qroilib/roilib/changeselectedarea.cpp \
           $$PWD/qroilib/roilib/compression.cpp \
           $$PWD/qroilib/roilib/createellipseobjecttool.cpp \
           $$PWD/qroilib/roilib/createmultipointobjecttool.cpp \
           $$PWD/qroilib/roilib/createobjecttool.cpp \
           $$PWD/qroilib/roilib/createpatternobjecttool.cpp \
           $$PWD/qroilib/roilib/createpointobjecttool.cpp \
           $$PWD/qroilib/roilib/createpolygonobjecttool.cpp \
           $$PWD/qroilib/roilib/createpolylineobjecttool.cpp \
           $$PWD/qroilib/roilib/createrectangleobjecttool.cpp \
           $$PWD/qroilib/roilib/createscalableobjecttool.cpp \
           $$PWD/qroilib/roilib/createtextobjecttool.cpp \
           $$PWD/qroilib/roilib/editpolygontool.cpp \
           $$PWD/qroilib/roilib/filesystemwatcher.cpp \
           $$PWD/qroilib/roilib/grouplayer.cpp \
           $$PWD/qroilib/roilib/hex.cpp \
           $$PWD/qroilib/roilib/hexagonalrenderer.cpp \
           $$PWD/qroilib/roilib/imagereference.cpp \
           $$PWD/qroilib/roilib/isometricrenderer.cpp \
           $$PWD/qroilib/roilib/layer.cpp \
           $$PWD/qroilib/roilib/layeritem.cpp \
           $$PWD/qroilib/roilib/layeroffsettool.cpp \
           $$PWD/qroilib/roilib/moveroiobject.cpp \
           $$PWD/qroilib/roilib/moveroiobjecttogroup.cpp \
           $$PWD/qroilib/roilib/objectgroup.cpp \
           $$PWD/qroilib/roilib/objectgroupitem.cpp \
           $$PWD/qroilib/roilib/objectselectionitem.cpp \
           $$PWD/qroilib/roilib/objectselectiontool.cpp \
           $$PWD/qroilib/roilib/objecttypes.cpp \
           $$PWD/qroilib/roilib/objecttypesmodel.cpp \
           $$PWD/qroilib/roilib/orthogonalrenderer.cpp \
           $$PWD/qroilib/roilib/properties.cpp \
           $$PWD/qroilib/roilib/propertiesdock.cpp \
           $$PWD/qroilib/roilib/propertybrowser.cpp \
           $$PWD/qroilib/roilib/qpatternroif.cpp \
           $$PWD/qroilib/roilib/resizeroiobject.cpp \
           $$PWD/qroilib/roilib/roimap.cpp \
           $$PWD/qroilib/roilib/roiobject.cpp \
           $$PWD/qroilib/roilib/roiobjectitem.cpp \
           $$PWD/qroilib/roilib/roiobjectmodel.cpp \
           $$PWD/qroilib/roilib/roireader.cpp \
           $$PWD/qroilib/roilib/roirenderer.cpp \
           $$PWD/qroilib/roilib/roiscene.cpp \
           $$PWD/qroilib/roilib/roitovariantconverter.cpp \
           $$PWD/qroilib/roilib/roiwriter.cpp \
           $$PWD/qroilib/roilib/rotateroiobject.cpp \
           $$PWD/qroilib/roilib/savefile.cpp \
           $$PWD/qroilib/roilib/selectionrectangle.cpp \
           $$PWD/qroilib/roilib/snaphelper.cpp \
           $$PWD/qroilib/roilib/toolmanager.cpp \
           $$PWD/qroilib/roilib/utils.cpp \
           $$PWD/qroilib/roilib/variantpropertymanager.cpp \
           $$PWD/qroilib/roilib/varianttomapconverter.cpp \

#RESOURCES += $$PWD/resources.qrc
#TRANSLATIONS += qroiapp_en.ts qroiapp_ko.ts
